import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Montserrat } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "../_components/theme-provider";
import { Suspense } from "react";
import { ClerkProvider } from "@clerk/nextjs";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.className} ${inter.className}`}>
        <div className="flex items-center min-h-screen w-full justify-around">
          <div className="w-6/12 justify-items-center">{children}</div>
          <div className="min-h-screen w-full overflow-hidden content-center box-border justify-items-center">
            <Image
              src={`/img/deliver.jpg`}
              alt="deliver"
              width={1000}
              height={1000}
              objectFit="cover"
            />
          </div>
        </div>
      </body>
    </html>
  );
}
